# This file "inherits" everything from the original
defaults:
  - /opt/nemo-rl/examples/configs/grpo_math_1B.yaml
  - _self_

# Only list the "fixes"
trainer:
  precision: bf16-mixed
  log_every_n_steps: 1

policy:
  precision: bfloat16
  model:
    torch_dtype: bfloat16
  model_name: Qwen/Qwen2.5-Coder-1.5B-Instruct
  tokenizer:
    name: Qwen/Qwen2.5-Coder-1.5B-Instruct

model:
  model_loader:
    torch_dtype: bfloat16
  generation:
    vllm_kwargs:
      dtype: bfloat16
      enforce_eager: true
      max_model_len: 512

grpo:
  num_generations: 2
  val_period: 0
  val_at_start: false