import ray
import requests
import re
from nemo_rl.data.processors import register_processor
from nemo_rl.environments.utils import register_env
from nemo_rl.environments.interfaces import EnvironmentInterface
from nemo_rl.data.datum import DatumSpec

# --- 1. The Data Processor ---
@register_processor("golang_processor")
def golang_processor(datum_dict, **kwargs):
    # This bypasses all 'problem' and 'expected_answer' requirements
    return DatumSpec(
        input=datum_dict.get("input", ""),
        # We pass the whole dict as metadata so the env can see 'test_code'
        extra_env_info=datum_dict, 
        is_correct=True # Hardcoded to True so NeMo doesn't 'pre-judge' the code
    )

# --- 2. The Environment Actor ---
@ray.remote
class GolangRemoteEnv(EnvironmentInterface):
    def __init__(self, config):
        # This comes from the 'env' section of your YAML
        self.base_url = config.get("base_urls")[0] 

    async def step(self, actions, extra_env_info=None):
        rewards = []
        for i, code_output in enumerate(actions):
            # Clean the markdown backticks often generated by LLMs
            clean_code = re.sub(r"```go\n|```", "", code_output)
            
            try:
                # Forward the code and the specific test cases to your Go server
                payload = {
                    "code": clean_code,
                    "test_code": extra_env_info[i].get("extra_env_info", {}).get("test_code", "")
                }
                response = requests.post(f"{self.base_url}", json=payload, timeout=10)
                reward = float(response.json().get("reward", 0.0))
            except Exception as e:
                print(f"Reward Server Error: {e}")
                reward = 0.0
            
            rewards.append(reward)
            
        # Return: (observations, rewards, terminateds, truncateds, infos)
        return [], rewards, [True] * len(actions), [False] * len(actions), {}

# --- 3. The Registration ---
def register_custom_components():
    # This manually injects our classes into the NeMo registries
    register_env("golang_bridge_env", GolangRemoteEnv)